// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Status struct {
	ID               int64
	Reading          string
	Message          string
	ReadingUpdatedAt time.Time
	MessageUpdatedAt time.Time
}
