CREATE TABLE status (
    id INTEGER PRIMARY KEY,
    reading TEXT NOT NULL DEFAULT '',
    message TEXT NOT NULL DEFAULT '',
    reading_updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    message_updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
