services:
  mimi-back:
    build: ./src
    container_name: mimi-back
    restart: unless-stopped
    environment:
      - GIN_MODE=release
    volumes:
      - ./data:/app/data
    networks:
      - red-homelab

networks:
  red-homelab:
    external: true
