// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"time"
)

const getStatus = `-- name: GetStatus :one
SELECT reading, message, reading_updated_at, message_updated_at FROM status WHERE id = 1
`

type GetStatusRow struct {
	Reading          string
	Message          string
	ReadingUpdatedAt time.Time
	MessageUpdatedAt time.Time
}

func (q *Queries) GetStatus(ctx context.Context) (GetStatusRow, error) {
	row := q.db.QueryRowContext(ctx, getStatus)
	var i GetStatusRow
	err := row.Scan(
		&i.Reading,
		&i.Message,
		&i.ReadingUpdatedAt,
		&i.MessageUpdatedAt,
	)
	return i, err
}

const updateMessage = `-- name: UpdateMessage :exec
UPDATE status SET message = ?, message_updated_at = CURRENT_TIMESTAMP WHERE id = 1
`

func (q *Queries) UpdateMessage(ctx context.Context, message string) error {
	_, err := q.db.ExecContext(ctx, updateMessage, message)
	return err
}

const updateReading = `-- name: UpdateReading :exec
UPDATE status SET reading = ?, reading_updated_at = CURRENT_TIMESTAMP WHERE id = 1
`

func (q *Queries) UpdateReading(ctx context.Context, reading string) error {
	_, err := q.db.ExecContext(ctx, updateReading, reading)
	return err
}
